# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "prb-remote-state"
    dynamodb_table = "prb-remote-state"
    encrypt        = true
    key            = "staging/us-east-1/ssm-parameters/terraform.tfstate"
    region         = "us-east-1"
  }
}
